apiVersion: v1
kind: "ReplicationController"
metadata:
  labels:
    app: "cdh"
  name: "cdh-rc"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "cdh"
      name: "cdh"
    spec:
      containers:
        image: "svds/cdh"
        name: "cdh"
