apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-world
  name: hello-world
spec:
  ports:
  - port: 80
    name: http
    targetPort: http
  selector:
    app: hello-world
  type: LoadBalancer
