apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: "MultiContainerApp"
  name: "hello-postgres"
spec:
  replicas: 1
  selector:
    app: "MultiContainerApp"
  template:
    metadata:
      labels:
        app: "MultiContainerApp"
  spec:
    containers:
    - image: "tutum/hello-world"
      name: "hello-world"
      ports:
      - containerPort: 8080
    - image: "postgres"
      name: "postgres"
      ports:
        - containerPort: 5432
