apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafkaApp
  name: kafka
spec:
  ports:
  - port: 9092
    name: "kafka"
    targetPort: 9092
  - port: 2181
    name: "zookeeper"
    targetPort: 2181
  selector:
    app: kafkaApp
  type: LoadBalancer
