apiVersion: v1
kind: ReplicationController
metadata:
  name: "mysql"
  labels:
    app: "mysql-app"
spec:
  replicas: 1
  selector:
    app: "mysql-app"
  template:
    metadata:
      labels:
        app: "mysql-app"
    spec:
      containers:
      - env:
        - name: "MYSQL_ROOT_PASSWORD"
          value: "mysql"
        image: "mysql"
        name: "mysql"
        ports:
        - containerPort: 3306
