apiVersion: v1
kind: ReplicationController
metadata:
  name: "oradb"
  labels:
    app: "oradb"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "oradb"
    spec:
      containers:
      - image: "sath89/oracle-xe-11g"
        name: "oradb"
