apiVersion: v1
kind: Pod
metadata:
  name: "oradb"
  labels:
    name: "oradb"
spec:
  containers:
  - image: "sath89/oracle-xe-11g"
    name: "oradb"
    ports:
    - containerPort: 1521
  restartPolicy: Always
