apiVersion: v1
kind: ReplicationController
metadata:
  name: "postgres"
spec:
  replicas: 2
  selector:
    app: "postgres"
  template:
    metadata:
      labels:
        app: "postgres"
    spec:
      containers:
      - image: "postgres"
        name: "postgres"

